config/routes.rb
Rails.application.routes.draw do
  resources :hearts
  devise_for :podcasts

  resources :charges
  

  resources :podcasts, only: [:index, :show] do
  	resources :episodes
  end

  authenticated :podcast do
  	root 'podcasts#dashboard', as: "authenticated_root" 
  end

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :podcast

  

  has_attached_file :episode_thumbnail, :styles => { :large => "1000x1000#", :medium => "550x550#" }
validates_attachment_content_type :episode_thumbnail, :content_type => /\Aimage\/.*\Z/

  
  has_attached_file :mp3
validates_attachment :mp3, :content_type => { :content_type => ["audio/mpeg", "audio/mp3"] }, :file_name => { :matches => [/mp3\Z/] }

end

app/models/heart.rb
class Heart < ApplicationRecord
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :episodes

  

  has_attached_file :thumbnail, :styles => { :large => "1000x1000#", :medium => "550x550#" }
validates_attachment_content_type :thumbnail, :content_type => /\Aimage\/.*\Z/


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :title, :thumbnail)}
  	devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :title, :thumbnail, :description)}
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
    end

 def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
	before_action :authenticate_podcast!, except: [:show]
	before_action :require_permission
	before_action :find_podcast
	before_action :find_episode, only: [:show, :edit, :update, :destroy]

	def new
		@episode = @podcast.episodes.new
	end

	def create
		@episode = @podcast.episodes.new episode_params
		if @episode.save
			redirect_to podcast_episode_path(@podcast, @episode)
		else
			render 'new'
		end
	end

	def show
		@episodes = Episode.where(podcast_id: @podcast).order("created_at DESC").reject { |e| e.id == @episode.id }
	end

	def edit
	end

	def update
		if @episode.update episode_params
			redirect_to podcast_episode_path(@podcast, @episode), notice: "Episode was succesfully updated!"
		else
			render 'edit'
		end
	end

	def destroy
		@episode.destroy
		redirect_to root_path
	end

	private

	def episode_params
		params.require(:episode).permit(:title, :description, :episode_thumbnail, :mp3)
	end

	def find_podcast
		@podcast = Podcast.find(params[:podcast_id])
	end

	def find_episode
		@episode = Episode.find(params[:id])
	end

	def require_permission
		@podcast = Podcast.find(params[:podcast_id])
		if current_podcast != @podcast
			redirect_to root_path, notice: "Sorry, you're not allowed to view that page"
		end
end
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
	before_action :find_podcast, only: [:show, :dashboard]
	before_action :find_episode, only: [:show, :dashboard]

	def index
		@podcasts = Podcast.all.order("created_at DESC")
	end

	def show
	end

	def dashboard
	end

	private

	def find_episode
		@episodes = Episode.where(podcast_id: @podcast).order("created_at DESC")
	end

	def find_podcast
		if params[:id].nil?
			@podcast = current_podcast
		else
			@podcast = Podcast.find(params[:id])
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/hearts_helper.rb
module HeartsHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/application/_footer.html.erb
    <section id="contact" style="">
            <div class="container">
                <div class="row">
                    <div class="about_our_company" style="margin-bottom: 20px;">
                        <h1 style="color:#fff;">Write Your Message</h1>
                        <div class="titleline-icon"></div>
                        <p style="color:#fff;">LessonPods </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-8">
                        <form name="sentMessage" id="contactForm" novalidate="">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Your Name *" id="name" required="" data-validation-required-message="Please enter your name.">
                                        <p class="help-block text-danger"></p>
                                    </div>
                                    <div class="form-group">
                                        <input type="email" class="form-control" placeholder="Your Email *" id="email" required="" data-validation-required-message="Please enter your email address.">
                                        <p class="help-block text-danger"></p>
                                    </div>
                                    <div class="form-group">
                                        <input type="tel" class="form-control" placeholder="Your Phone *" id="phone" required="" data-validation-required-message="Please enter your phone number.">
                                        <p class="help-block text-danger"></p>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <textarea class="form-control" placeholder="Your Message *" id="message" required="" data-validation-required-message="Please enter a message."></textarea>
                                        <p class="help-block text-danger"></p>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                                <div class="col-lg-12 text-center">
                                    <div id="success"></div>
                                    <button type="submit" class="btn btn-xl get">Send Message</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-4">
                        <p style="color:#fff;">
                            <strong><i class="fa fa-map-marker"></i> Address</strong><br>
                            1216/Mirpur_10 Beach, Dhaka(Bangladesh)
                        </p>
                        <p style="color:#fff;"><strong><i class="fa fa-phone"></i> Phone Number</strong><br>
                            (+8801)7123456</p>
                        <p style="color:#fff;">
                            <strong><i class="fa fa-envelope"></i>  Email Address</strong><br>
                            Email@info.com</p>
                        <p></p>
                    </div>
                </div>
            </div>
        </section>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/episodes/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://lessonpods.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            

app/views/episodes/_form.html.erb
<%= form_for ([@podcast, @episode]) do |f| %>

	<div class="field">
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</div>

	<div class="field">
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</div>

	<div class="field">
		<%= f.label :episode_thumbnail %><br>
		<%= f.file_field :episode_thumbnail %>
	</div>
	<div class="field">
		<%= f.label :mp3 %><br>
		<%= f.file_field :mp3 %>
    </div>

	<%= f.submit class: "button button_highlight button_block" %>
<% end %>

app/views/episodes/edit.html.erb
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
      <h1><%= @podcast.title %></h1>
    </div>
  </div>

  <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li><%= link_to "Lessons", root_path, class: "button button_highlight button_block" %></li>
        <li><%= link_to "New Lesson", new_podcast_episode_path(@podcast), class: "button button_highlight button_block" %></li>
        <li><%= link_to "Account Settings", edit_podcast_registration_path, class: "button button_highlight button_block" %></li>
        <li><%= link_to "View Podcast", podcast_path(current_podcast), class: "button button_highlight button_block" %></li>
      </ul>
    </div>
  </div>
  <hr>

  <div id="form">
	  <div class="wrapper_skinny">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/episodes/new.html.erb
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
      <h1><%= @podcast.title%></h1>
    </div>
  </div>

  <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li><%= link_to "Lessons", root_path, class: "button button_highlight button_block" %></li>
        <li><%= link_to "New Lesson", new_podcast_episode_path(@podcast), class: "button button_highlight button_block" %></li>
        <li><%= link_to "Account Settings", edit_podcast_registration_path, class: "button button_highlight button_block" %></li>
        <li><%= link_to "View Podcast", podcast_path(current_podcast), class: "button button_highlight button_block" %></li>
      </ul>
    </div>
  </div>
  <hr>

  <div id="form">
    <div class="wrapper_skinny">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/episodes/show.html.erb
<div id="podcast_show">
	<div id="show_banner">
		<div class="wrapper_skinny">
			<h1><%= @podcast.title %></h1>
			<p class="description"><%= @podcast.description %></p>
			
		</div>
	</div>

	<div id="breadcrumb">
		<%= link_to podcasts_path do %>
			All Podcasts
			<span>/</span>
			<%= link_to @podcast.title, podcast_path(@podcast) %>
			<span>/</span>
			<%= @episode.title %>
		<% end %>
	</div>

	<div id="episode_content">
		<div class="wrapper_skinny">
			<%= image_tag @episode.episode_thumbnail.url(:medium), class: "current_episode_thumbnail" %>
			<h2><%= @episode.title %></h2>
			<p class="description"><%= @episode.description %></p>

			<div id="jquery_jplayer_1" class="jp-jplayer"></div>
      <div id="jp_container_1" class="jp-audio">
        <div class="jp-type-single">
          <div class="jp-gui jp-interface">
            <ul class="jp-controls">
              <li><a href="javascript:;" class="jp-play" tabindex="1">&#61515;</a></li>
              <li><a href="javascript:;" class="jp-pause" tabindex="1">&#61516;</a></li>
              <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">&#61480;</a></li>
              <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">&#61478;</a></li>
            </ul>

            <div class="jp-progress">
              <div class="jp-seek-bar">
                <div class="jp-play-bar"></div>
              </div>
            </div>

            <div class="jp-time-holder">
              <div class="jp-current-time"></div>
            </div>

            <div class="jp-volume-bar">
              <div class="jp-volume-bar-value"></div>
            </div>

            <div class="jp-no-solution">
              <span>Update Required</span>
              To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
            </div>
          </div>
        </div>
</div>
		</div>
	</div>


	<div id="episodes">
		<div class="wrapper_skinny">
			<ul class="cf">
				<% @episodes.each do |episode| %>
					<li class="cf">
						<div class="episode_thumbnail">
							<a href="episode.html">
								<%= image_tag episode.episode_thumbnail.url(:medium) %>
							</a>
						</div>
						<div class="episode_overview">
							<h2><%= link_to episode.title, podcast_episode_path(@podcast, episode) %></h2>
							<p class="description"><%= truncate(episode.description, length: 160) %></p>
						</div>
					</li>
				<% end %>
			</ul>
        </div>
	</div>
</div>
<%= render 'disqus' %>

<div class="pagination">
	<span class="previous_page disabled">Previous</span>
	<em class="current">1</em>
	<a href="#">2</a>
	<a class="next_page" href="#">Next</a>
</div>

<button id="toggle-box" >toggle</button>
<div id="box" style="display: none;"></div>

<script>
	$(document).ready(function(){
	  $("#jquery_jplayer_1").jPlayer({
	    ready: function () {
	      $(this).jPlayer("setMedia", {
	        mp3: "<%= @episode.mp3.url %>",
	      });
	    },
	    swfPath: "/js",
	    supplied: "mp3"
	  });
	});
	</script>

	<script>
		$('#toggle-box').click().toggle(function() {
    
    $('#box').animate({ width: 'show' });
});
	</script>

app/views/layouts/_header.html.erb
<header id="main_header" class="cf">
	<div class="wrapper_wide">
		<%= link_to "LessonPods", root_path, id: "logo" %>
		<nav>
			<ul>
				<% unless podcast_signed_in? %>
					<li><%= link_to "Explore", podcasts_path %></li>
					<li><%= link_to "Sign In", new_podcast_session_path %></li>
					<li><%= link_to "Create a Podcast", new_podcast_registration_path %></li>
				<% else %>
					<li><%= link_to "Dashboard", root_path %></li>
					<li><%= link_to "Explore", podcasts_path %></li>
					<li><%= link_to "Sign Out", destroy_podcast_session_path, method: :delete %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LessonPods</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,700,300italic,700italic' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
     <script src="https://code.jquery.com/jquery-3.0.0.min.js"></script>
     

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrp-theme.min.css">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  
<meta name="viewport" content="width=device-width, initial-scale=1.0">


  </head>

  <body>
  <% if alert %>
  <p class="alert"><%= alert %></p>
    <% elsif notice %>
  <p class="notice"><%= notice %></p>
  <% end %>
  <% unless current_page?(root_path) %>
	<%= render 'layouts/header'; %>
  <% end %>
 <%= yield %>


 <%= render 'footer'; %>

  </body>
</html>

app/views/podcasts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://lessonpods.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            

app/views/podcasts/_section.html.erb
<div class="container">
    <div class="col-sm-12">

                

                <div class="bs-calltoaction bs-calltoaction-primary">
                    <div class="row">
                        <div class="col-md-9 cta-contents">
                            <h1 class="cta-title">Sign Up</h1>
                        </div>
                     </div>
                </div>

                <div class="bs-calltoaction bs-calltoaction-info">
                     <div class="row">
                        <div class="col-md-9 cta-contents">
                            <h1 class="cta-title">Go to Dashboard</h1>
                        </div>
                     </div>
                </div>
                        
                     
                

                <div class="bs-calltoaction bs-calltoaction-success">
                    <div class="row">
                        <div class="col-md-9 cta-contents">
                            <h1 class="cta-title">Update Account Settings</h1>
                        </div>
                     </div>
                </div>
                        
                    
                

                <div class="bs-calltoaction bs-calltoaction-warning">
                    <div class="row">
                        <div class="col-md-9 cta-contents">
                            <h1 class="cta-title">Create a new lesson</h1>
                        </div>
                     </div>
                </div>
                        
                     
                

                <div class="bs-calltoaction bs-calltoaction-danger">
                    <div class="row">
                        <div class="col-md-9 cta-contents">
                            <h1 class="cta-title">That's it!</h1>
                        </div>
                     </div>
                </div>
                        
                     </div>
                </div>

   </div>
</div>

app/views/podcasts/dashboard.html.erb
<%= render 'layouts/header'; %>

<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
      <h1><%= @podcast.title %></h1>
    </div>
  </div>

  
 <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li><%= link_to "Lessons", root_path, class: "button button_highlight button_block" %></li>
        <li><%= link_to "New Lesson", new_podcast_episode_path(@podcast), class: "button button_highlight button_block" %></li>
        <li><%= link_to "Account Settings", edit_podcast_registration_path, class: "button button_highlight button_block" %></li>
        <li><%= link_to "View Podcast", podcast_path(current_podcast), class: "button button_highlight button_block" %></li>
      </ul>
    </div>
  </div>
<a href="https://twitter.com/intent/tweet?button_hashtag=LessonPOds" class="twitter-hashtag-button" data-size="large" data-related="shiks_tony">Tweet #LessonPOds</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
<hr>
  <div id="episodes">
    <div class="wrapper_skinny">
      <ul class="cf">
        <% @episodes.each do |episode| %>
          <li class="cf">
            <div class="episode_thumbnail">
              <a href="episode.html">
                <%= image_tag episode.episode_thumbnail.url(:medium) %>
              </a>
            </div>
            <div class="episode_overview">
              <h2><%= link_to episode.title, podcast_episode_path(@podcast, episode) %></h2>
              <p class="description"><%= truncate(episode.description, lenght: 160) %></p>
              <div class="authorized_links">
                <%= link_to "Edit", edit_podcast_episode_path(@podcast, episode), class: "button button_danger" %>
                <%= link_to "Delete", podcast_episode_path(@podcast, episode), method: :delete, data: {confirm: "Are you sure?"} %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<hr>
<%= render 'disqus' %>

<div class="pagination">
<span class="previous_page disabled">Previous</span>
<em class="current">1</em>
<a href="#">2</a>
<a class="next_page" href="#">Next</a>
</div>

app/views/podcasts/index.html.erb
<div id="banner" class="podcasts_banner">
	<h1>Discover your new favorite podcast</h1>
</div>

<div id="podcasts" class="cf">
	<div class="wrapper">
		<ul class="cf">
			<% @podcasts.each do |podcast| %>
				<%= link_to podcast do %>
					<li>
						<%= image_tag podcast.thumbnail.url(:medium) %>
						<div class="podcast_overview">
							<h2><%= podcast.title %></h2>
							<p class="episode_count">1 Episode</p>
						</div>
					</li>
				<% end %>
			<% end %>
		</ul>
	</div>
</div>

<div class="item">
    <h2 align="center">How it works!</h2>
    <%= render 'section' %>
 </div>

app/views/podcasts/show.html.erb
<div id="podcast_show">
	<div id="show_banner">
		<div class="wrapper_skinny">
			<h1><%= @podcast.title %></h1>
			<p class="description"><%= @podcast.description %></p>
			
		</div>
	</div>

	<div id="breadcrumb">
		<%= link_to podcasts_path do %>
			All Podcasts
			<span>/</span>
			<%= @podcast.title %>
		<% end %>
	</div>

	<div id="episodes">
		<div class="wrapper_skinny">
			<ul class="cf">
				<% @episodes.each do |episode| %>
					<li class="cf">
						<div class="episode_thumbnail">
							<a href="#">
								<%= image_tag episode.episode_thumbnail.url(:medium) %>
							</a>
						</div>
						<div class="episode_overview">
							<h2><%= link_to episode.title, podcast_episode_path(@podcast, episode) %></h2>
							<p class="description"><%= truncate(episode.description, length: 160) %></p>
						</div>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<div id="background">
	<header class="cf">
		<div class="wrapper_wide">
			<a href="index.html" id="logo">LessonPods</a>
			<nav>
				<ul>
				<% unless podcast_signed_in? %>
					<li><%= link_to "Explore", podcasts_path %></li>
					<li><%= link_to "Sign In", new_podcast_session_path %></li>
					<li><%= link_to "Create a Podcast", new_podcast_registration_path %></li>
					<%else%>
					<li><%= link_to "Explore", podcasts_path %></li>
					<li><%= link_to "Sign Out", destroy_podcast_session_path, method: :delete %></li>
					<% end %>
				</ul>
			</nav>
		</div>

	</header>
	<div class="wrapper_skinny">
	<h1>Discover your new favourite<br> podcast, or create your own.</h1>
	<%= link_to "Create a Podcast", new_podcast_registration_path, class:"button button_highlight"%>
	<%= link_to "Explore", podcasts_path, class: "button button_white" %>
	</div>
</div>